### ISSUE TITLE
Latest Release does not boot on Redmi Note 12 Pro Plus MiUi 14.0.9 Android 12

### ISSUE THREAD

**Issue by Error-106** [Coconutat/android_kernel_xiaomi_ruby_exp#1]
Black screen when trying to start
A reboot occurs later

**Comment by Error-106** [comment]
![Screenshot_2023-09-25-18-48-28-298_com android settings-edit](https://github.com/Coconutat/android_kernel_xiaomi_ruby_exp/assets/92155028/56737b83-67d7-434d-ad45-38202b81235b)

**Comment by Error-106** [comment]
rom in this: https://xiaomifirmwareupdater.com/miui/ruby/stable/V14.0.9.0.SMOCNXM/

**Comment by Coconutat** [comment]
Rom has Any modify？E.g：Install Magisk or TWRP？

**Comment by Coconutat** [comment]
I only know 14.0.3 is fine.

**Comment by Error-106** [comment]
Install Magisk only

**Comment by Error-106** [comment]
This problem also occurs with the original boot.img

**Comment by Error-106** [comment]
I noticed that there are two different Android versions (Android 12 and 13)

**Comment by Error-106** [comment]
Does the Android version have an impact on this?

**Comment by Error-106** [comment]
Gonon-Kernel/ruby-release has the same issue but is not explicitly available for Android 12 and Redmi Note 12 Pro Plus

**Comment by Error-106** [comment]
the kernel is build for MIUI global?
If because of this, the screen should not be black at startup.

**Comment by Coconutat** [comment]
I use xiaomi official released open source kernel.It support Android S(12).I think you need uninstall all magisk modules and magisk.Then install it.

**Comment by Coconutat** [comment]
I use xiaomi official released open source kernel.It support Android S(12).I think you need uninstall all magisk modules and magisk.Then install it.

**Comment by Coconutat** [comment]
> the kernel is build for MIUI global? If because of this, the screen should not be black at startup.

Nah,It for CN.

**Comment by Coconutat** [comment]
> the kernel is build for MIUI global? If because of this, the screen should not be black at startup.

You can send me a config.gz.Then I can do some research.File path is /proc/config.gz.

**Comment by Error-106** [comment]
> I use xiaomi official released open source kernel.It support Android S(12).I think you need uninstall all magisk modules and magisk.Then install it.

I try to use origin boot.img, it still have same issue

**Comment by Error-106** [comment]
> > the kernel is build for MIUI global? If because of this, the screen should not be black at startup.
> 
> You can send me a config.gz.Then I can do some research.File path is /proc/config.gz.

lanzouw.com/iqD5e19xxvtc

**Comment by Coconutat** [comment]
> > I use xiaomi official released open source kernel.It support Android S(12).I think you need uninstall all magisk modules and magisk.Then install it.
> 
> I try to use origin boot.img, it still have same issue

Nah,I mean fully uninstall.Use Magisk APP uninstall it.Then restore original boot.

**Comment by Coconutat** [comment]
> > > the kernel is build for MIUI global? If because of this, the screen should not be black at startup.
> > 
> > 
> > You can send me a config.gz.Then I can do some research.File path is /proc/config.gz.
> 
> lanzouw.com/iqD5e19xxvtc
I compared the defconfig file you provided me with the stock defconfig I extracted. The contents of these two files are identical, and the hash value is the same.I think your ROM has been modified, causing it to be not clean enough.

**Comment by Coconutat** [comment]
> > > the kernel is build for MIUI global? If because of this, the screen should not be black at startup.
> > 
> > 
> > You can send me a config.gz.Then I can do some research.File path is /proc/config.gz.
> 
> lanzouw.com/iqD5e19xxvtc

***  
I compared the defconfig file you provided me with the stock defconfig I extracted. The contents of these two files are identical, and the hash value is the same.I think your ROM has been modified, causing it to be not clean enough.

**Comment by Error-106** [comment]
> > > I use xiaomi official released open source kernel.It support Android S(12).I think you need uninstall all magisk modules and magisk.Then install it.
> > 
> > 
> > I try to use origin boot.img, it still have same issue
> 
> Nah,I mean fully uninstall.Use Magisk APP uninstall it.Then restore original boot.

Attempted to restore all masigk changes, it still have same issue

**Comment by Error-106** [comment]
> > > > the kernel is build for MIUI global? If because of this, the screen should not be black at startup.
> > > 
> > > 
> > > You can send me a config.gz.Then I can do some research.File path is /proc/config.gz.
> > 
> > 
> > lanzouw.com/iqD5e19xxvtc
> 
> I compared the defconfig file you provided me with the stock defconfig I extracted. The contents of these two files are identical, and the hash value is the same.I think your ROM has been modified, causing it to be not clean enough.

i will try reflash rom

**Comment by Coconutat** [comment]
> > > > > the kernel is build for MIUI global? If because of this, the screen should not be black at startup.
> > > > 
> > > > 
> > > > You can send me a config.gz.Then I can do some research.File path is /proc/config.gz.
> > > 
> > > 
> > > lanzouw.com/iqD5e19xxvtc
> > 
> > 
> > I compared the defconfig file you provided me with the stock defconfig I extracted. The contents of these two files are identical, and the hash value is the same.I think your ROM has been modified, causing it to be not clean enough.
> 
> i will try reflash rom

***
Try this:https://github.com/Coconutat/android_kernel_xiaomi_ruby_exp/releases/tag/KSU_0.6.8%2B

**Comment by Error-106** [comment]
Is there a boot.img that has been patched? I do not have third-party recovery and root permissions.(or I used Android-Image-Kitchen to patch boot.img?)

**Comment by Error-106** [comment]
I used Android-Image-Kitchen to patch boot.img , it still have same issue

**Comment by Error-106** [comment]
Maybe this kernel cannot run on MiUi 14.0.9

**Comment by Coconutat** [comment]
> Maybe this kernel cannot run on MiUi 14.0.9也许这个内核不能在MiUi 14.0.9上运行

很有可能。

**Comment by Coconutat** [comment]
> Maybe this kernel cannot run on MiUi 14.0.9

Yeah,I think so.

**Comment by Coconutat** [comment]
> Maybe this kernel cannot run on MiUi 14.0.9

Right now,Wating for Xiaomi Release A13 Version Kernel。

**Comment by Coconutat** [comment]
> Maybe this kernel cannot run on MiUi 14.0.9

I asked some tester.This kernel support A13.A12 won’t boot.I only now know that MIUI 14.0.3 is Android 13 and MIUI 14.0.9 is Android 12.I can’t understand.

**Comment by Error-106** [comment]
There seem to be some hardware differences between Android 12 and Android 13 devices, and I can't use the Android 13 version of ROM on my device.
:(

**Comment by Error-106** [comment]
Are there plans for Android 12 support?

**Comment by Coconutat** [comment]
> Are there plans for Android 12 support?

I don't know what your phone development code is.If have little hardware difference,Xiaomi should be Open Source in another repo.

**Comment by Error-106** [comment]
maybe is 'rubypro'？

**Comment by Coconutat** [comment]
> maybe is 'rubypro'？  
***
Use this to get code name:  
```
fastboot getvar product
```

**Comment by Error-106** [comment]
I'm pretty sure my development code is RubyPro.There are kernel versions and hardware versions.![Screenshot_2023-11-05-23-48-23-852_com.android.settings.jpg](https://github.com/Coconutat/android_kernel_xiaomi_ruby_exp/assets/92155028/6ecd1e61-e251-4b1e-a49a-58af5586e0ea)

**Comment by Coconutat** [comment]
> I'm pretty sure my development code is RubyPro.There are kernel versions and hardware versions.![Screenshot_2023-11-05-23-48-23-852_com.android.settings.jpg](https://user-images.githubusercontent.com/92155028/280538413-6ecd1e61-e251-4b1e-a49a-58af5586e0ea.jpg)

Just reboot to fastboot.And use this:
```
fastboot getvar product
```

**Comment by Error-106** [comment]
My device can be upgraded to 14.0.5.0.TMOCNXM version now
![Screenshot_2023-12-10-18-29-56-642_com.android.updater.jpg](https://github.com/Coconutat/android_kernel_xiaomi_ruby_exp/assets/92155028/cfeae4f2-7347-4d81-a72b-f27eaf3732dc)

Does it work now?

**Comment by Coconutat** [comment]
> My device can be upgraded to 14.0.5.0.TMOCNXM version now ![Screenshot_2023-12-10-18-29-56-642_com.android.updater.jpg](https://private-user-images.githubusercontent.com/92155028/289352166-cfeae4f2-7347-4d81-a72b-f27eaf3732dc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMTEzMDYsIm5iZiI6MTcwMjIxMTAwNiwicGF0aCI6Ii85MjE1NTAyOC8yODkzNTIxNjYtY2ZlYWU0ZjItNzM0Ny00ZDgxLWE3MmItZjI3ZWFmMzczMmRjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEwVDEyMjMyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyY2JiNmFlOWVkZTc4OWU2NjE2MjIzM2M3M2Y3MjllMGJlNDU4MThiYmYxN2JmNmY5NjhiNDQ2ZDVhNGFmMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gaW8QEmQ86Jf0rK__XFEuZn6cD30fed4EG2pR-tSekE)
> 
> Does it work now?

I don’t know.Hope you can test.QAQ

**Comment by Error-106** [comment]
It worked, but the system warned me that there was a problem inside my device

**Comment by Error-106** [comment]
When the system boot is complete, Android System sends a warning "There's an internal problem with your device.contact your manufacturer for details." I also noticed that there seemed to be a temporary anomaly in the brightness of the screen.Is this normal? I can try running factory tests if needed.

**Comment by Coconutat** [comment]
> When the system boot is complete, Android System sends a warning "There's an internal problem with your device.contact your manufacturer for details." I also noticed that there seemed to be a temporary anomaly in the brightness of the screen.Is this normal? I can try running factory tests if needed.

Not a normal mode.If it can be used normally. I suggest keeping it this way for now. If there are many additional bugs, I suggest you use the original factory boot.img or Magisk modified boot first.

**Comment by Error-106** [comment]
CIT is passed,Functions are all working fine,there seems to be some UI bugs.![Screenshot_2023-12-11-13-20-07-965_com.miui.home.jpg](https://github.com/Coconutat/android_kernel_xiaomi_ruby_exp/assets/92155028/65e7c4c3-2ef5-49f9-bd0f-dc8cafdbad10)

**Comment by Coconutat** [comment]
> CIT is passed,Functions are all working fine,there seems to be some UI bugs.![Screenshot_2023-12-11-13-20-07-965_com.miui.home.jpg](https://private-user-images.githubusercontent.com/92155028/289432950-65e7c4c3-2ef5-49f9-bd0f-dc8cafdbad10.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyODE2NjcsIm5iZiI6MTcwMjI4MTM2NywicGF0aCI6Ii85MjE1NTAyOC8yODk0MzI5NTAtNjVlN2M0YzMtMmVmNS00OWY5LWJkMGYtZGM4Y2FmZGJhZDEwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA3NTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkM2Y5M2JjOTk2NzExYzFlOWEyMDA0MjM4YTdhYTk1MWJlYWIyNGM1MWM4ZWM1ZTY5YjA0NzcwNmNiMDdjYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jJ0cDt1UHeuqhM02wAgGXdF6PRpKZr0EA8H-nd6ag4)

看上去还行。不太影响。
