### ISSUE TITLE
Device codename 

### ISSUE THREAD

**Issue by esk6a** [Coconutat/android_kernel_xiaomi_ruby_exp#2]
Hi there you've mentioned that this belongs to Redmi note 12 pro and pro + I was wondering by saying Redmi note 12 pro did you mean #ruby or #sweet_k6a ? Or both? Thank you.

**Comment by Coconutat** [comment]
> Hi there you've mentioned that this belongs to Redmi note 12 pro and pro + I was wondering by saying Redmi note 12 pro did you mean #ruby or #sweet_k6a ? Or both? Thank you.

Sorry for late.I am so busy.Actually, I'm not quite sure. If you want to know, you can obtain it through this command after entering fastboot mode.  
```
fastboot getvar product
```
Then you will find your device product name.
